<?php

namespace Nashville\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
    public function findAllAlphabetically() {
        return $this->createQueryBuilder('p')
            ->orderBy('p.name','ASC')
            ->getQuery()
            ->execute();
    }
}
