security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        
        secured_area:
            pattern:    ^/
          #  form_login:
          #      check_path: _security_check
          #      login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
     #   - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY}
     #   - { path: ^/products/new, roles: IS_AUTHENTICATED_FULLY}
       # - { path: ^/main, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }