parameters:
#    product.example.class: Nashville\ProductBundle\Example
    product.path: Nashville\ProductBundle
    
    
services:
#    product.example:
#        class: %product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_product_serializer:
        class: %product.path%\Serializer\ProductSerializer
        arguments: [@router]
        
    my_language_listener:
        class: %product.path%\EventListener\LanguageListener
        arguments: [@logger]
        tags:
            -
              name: kernel.event_listener
              event: kernel.request
              method: onKernelRequest